### ISSUE TITLE
Doesn't work on IE 11

### ISSUE THREAD

**Issue by leandroferreira** [G-Rath/webpack-serve-overlay#10]
`errorOverlay.js` uses ES6 features that are not compatible with IE 11, and there's no build script for transpiling it.

I can start working on a patch right away if you can give me your feedback on the approach, so either:

1. keep the syntax and add `babel`, or
2. remove arrow functions and template literals to keep the code compatible with ES5

**Comment by omniverse** [comment]
I think option 1. makes sense, since arrow functions and template literals are here to stay. It will require fewer changes overall. Thanks!

**Comment by G-Rath** [comment]
@leandroferreira I would be interested in seeing what the build/publish flow would look like with `babel`, as I'm not too confident with that yet. (I've used `babel`, but never setup a package that got published with it before)

However, `webpack-serve` is actually deprecated, so development on this package isn't really happening.

My advice would be to transpile the vendor package; This isn't the only package out there that doesn't target ES5 (looking at you `query-string` & `strict-uri-encode`).

I'll have a look at any PR you submit, but again, can't promise anything due to the deprecation of `webpack-serve`.

I'm also wanting to avoid touching the code for option 2 in general b/c it came from the original overlay, and the less I modify of that the better, so that they're in sync.

**Comment by leandroferreira** [comment]
Agreed, will close the issue unless someone wants to work on this.
